Repository ii-sol/frontend, pull requests merged in 2024-06, with the labels that each got.

#1 init: twin.macro 세팅
  package.json
  src/assets/react.svg
  src/index.css
  src/main.jsx
  src/styles/GlobalStyles.jsx
  tailwind.config.js
  vite.config.js
Labels: 🍽️ init

#2 init: 라우터 설정
  src/App.jsx
  src/router/main-router.jsx
Labels: 🍽️ init

#3 init: 레이아웃, api 모듈화, redux 기본 세팅
  src/pages/layout/InsideLayout.jsx
  src/pages/layout/MainLayout.jsx
  src/pages/layout/NavLayout.jsx
  src/services/api.jsx
  src/store/stores.jsx
Labels: 🍽️ init

#8 feat: navbar
  src/assets/img/Home/alert.svg
  src/assets/img/Home/mypage.svg
  src/components/Nav/Navbar.jsx
  src/pages/Home/Common/Home.jsx
  src/pages/layout/NavLayout.jsx
  src/router/main-router.jsx
  src/styles/GlobalStyles.jsx
Labels: ✨ feature

#9 feat: Home 부모 아이 페이지
  src/pages/Home/Child/Home.jsx
  src/pages/Home/Child/HomeC.jsx
  src/pages/Home/Common/Home.jsx
  src/pages/Home/Parent/Home.jsx
  src/pages/Home/Parent/HomeP.jsx
  src/pages/Loan/Child/FromWho.jsx
  src/pages/Loan/Child/Money.jsx
  src/router/main-router.jsx
Labels: ✨ feature

#17 Feature/16 investment
  package.json
  src/assets/img/Invest/delete.svg
  src/assets/img/Invest/note.svg
  src/assets/img/Invest/suggest.svg
  src/assets/img/Invest/whitenote.svg
  src/components/Investment/Header.jsx
  src/components/Investment/PortfolioDonut.jsx
  src/components/Investment/PortfolioList.jsx
  src/components/Investment/StocksAbout.jsx
  src/components/Investment/StocksDetail.jsx
  src/components/common/Account.jsx
  src/components/common/Example.jsx
  src/components/common/Message.jsx
  src/components/mainInnerLayout.jsx
  src/index.css
  src/main.jsx
  src/pages/Home/Common/Home.jsx
  src/pages/Invest/Invest.jsx
  src/pages/Investment/Child/AvailableInvest.jsx
  src/pages/Investment/Child/Suggestion.jsx
  src/pages/Investment/Child/Trading.jsx
  src/pages/Investment/InvestMain.jsx
  src/pages/layout/InsideLayout.jsx
  src/router/main-router.jsx
  src/styles/GlobalStyles.jsx
Labels: ✨ feature

#26 feat: 종목 추가
  src/assets/img/Invest/blankStar.svg
  src/assets/img/Invest/filledStar.svg
  src/assets/img/Invest/search.svg
  src/components/Investment/StocksDetail.jsx
  src/components/common/Message.jsx
  src/pages/Investment/Child/AvailableInvest.jsx
  src/pages/Investment/Child/Done.jsx
  src/pages/Investment/Child/ParentSelection.jsx
  src/pages/Investment/Child/Suggestion.jsx
  src/pages/Investment/Child/Trading.jsx
  src/pages/Investment/StockList.jsx
  src/router/main-router.jsx
Labels: ✨ feature

#33 feat: 미션 요청하기 완료
  package.json
  src/assets/img/Auth/complete.png
  src/assets/img/Auth/kid.png
  src/assets/img/Auth/parent.png
  src/assets/img/Mission/missionMain.svg
  src/assets/img/common/complete.svg
  src/assets/img/common/empty.svg
  src/components/Mission/DueDateBottomSheet.jsx
  src/components/Mission/MissionCard.jsx
  src/components/Mission/MissionHistoryListItem.jsx
  src/components/Mission/RequestCard.jsx
  src/components/Mission/calendar/CalendarBody.jsx
  src/components/Mission/calendar/CalendarHeader.jsx
  src/components/Mission/calendar/SelectedDate.jsx
  src/components/Mission/calendar/index.jsx
  src/components/Mission/calendar/useCalendarContext.jsx
  src/components/common/Button.jsx
  src/components/common/Example.jsx
  src/components/common/History/Filter.jsx
  src/components/common/History/HistoryList.jsx
  src/components/common/Keypad.jsx
  src/components/common/Message.jsx
  src/components/mainInnerLayout.jsx
  src/index.css
  src/pages/Allowance/Allowance.jsx
  src/pages/Invest/Invest.jsx
  src/pages/Mission/Child/CreateMission.jsx
  src/pages/Mission/Child/CreateMissionComplete.jsx
  src/pages/Mission/Child/CreateMissionMember.jsx
  src/pages/Mission/Child/CreateMissionPrice.jsx
  src/pages/Mission/Child/MissionDetail.jsx
  src/pages/Mission/Child/MissionHistory.jsx
  src/pages/Mission/Child/MissionReceiveDetail.jsx
  src/pages/Mission/Child/MissionSendDetail.jsx
  src/pages/Mission/Mission.jsx
  src/router/main-router.jsx
  src/store/reducers/Auth/user.jsx
  src/store/reducers/Mission/mission.jsx
  src/store/stores.jsx
  src/styles/GlobalStyles.jsx
Labels: ✨ feature

#34 feat: 아이 용돈 조르기 페이지 수정
  src/components/Allowance/RegularAllowanceCard.jsx
  src/components/Allowance/RequestCardChild.jsx
  src/pages/Allowance/Child/AllowanceRequest.jsx
  src/pages/Allowance/Parent/AllowanceManagement.jsx
  src/pages/MyPage/My.jsx
Labels: ✨ feature

#35 feat: 아이 마이페이지 완성
  src/assets/img/MyPage/faq.svg
  src/assets/img/MyPage/search.svg
  src/assets/img/MyPage/service.svg
  src/assets/img/common/character/character_lay.svg
  src/assets/img/common/character/character_lulu.svg
  src/assets/img/common/character/character_moli.svg
  src/assets/img/common/character/character_pli.svg
  src/assets/img/common/character/character_sol.svg
  src/components/MyPage/Profile.jsx
  src/components/common/Member.jsx
  src/pages/MyPage/MemberManagement.jsx
  src/pages/MyPage/MyPage.jsx
  src/router/main-router.jsx
Labels: ✨ feature

#37 feat: 투자 페이지 리덕스 전역 관리
  src/components/Investment/CandleChart.jsx
  src/components/Investment/Header.jsx
  src/components/Investment/HistoryListItem.jsx
  src/components/Investment/Indicator.jsx
  src/components/Investment/PortfolioDonut.jsx
  src/components/Investment/PortfolioList.jsx
  src/components/Investment/StockItem.jsx
  src/components/Investment/StocksAbout.jsx
  src/components/Investment/StocksDetail.jsx
  src/components/Investment/SuggestionDetail.jsx
  src/components/common/Message.jsx
  src/pages/Investment/Child/AvailableInvest.jsx
  src/pages/Investment/Child/Done.jsx
  src/pages/Investment/Child/ParentSelection.jsx
  src/pages/Investment/Child/Suggestion.jsx
  src/pages/Investment/Child/SuggestionDetail.jsx
  src/pages/Investment/Child/Trading.jsx
  src/pages/Investment/InvestHistory.jsx
  src/pages/Investment/InvestMain.jsx
  src/router/main-router.jsx
  src/store/reducers/Invest/invest.jsx
  src/store/stores.jsx
  src/styles/GlobalStyles.jsx
Labels: ✨ feature

#53 Feature/43 notification
  package.json
  src/assets/img/Noti/allowance2.svg
  src/assets/img/Noti/etc2.svg
  src/assets/img/Noti/invest2.svg
  src/assets/img/Noti/loan2.svg
  src/assets/img/Noti/mission2.svg
  src/components/Notification/Filter.jsx
  src/components/Notification/Item.jsx
  src/components/Notification/NotiList.jsx
  src/components/mainInnerLayout.jsx
  src/index.css
  src/pages/Home/Common/Home.jsx
  src/pages/Home/Home.jsx
  src/pages/Notification/Notification.jsx
  src/pages/layout/MainLayout.jsx
  src/router/main-router.jsx
  src/services/api.jsx
  src/services/notifications.jsx
  src/store/reducers/Invest/invest.jsx
  src/store/reducers/Noti/notification.jsx
  src/store/stores.jsx
  src/utils/FetchSSE.jsx
  src/utils/Toast.jsx
  src/utils/groupDataByDate.jsx
Labels: ✨ feature

#56 fix: 덮어써진 Date 객체 복구
  src/components/Notification/NotiList.jsx
Labels: 🐛 bug fix

#58 Feature/43 notification
  package.json
  src/components/Investment/StockItem.jsx
  src/components/Notification/Item.jsx
  src/components/Notification/NotiList.jsx
  src/components/common/Alert/CheckDeleteNoti.jsx
  src/components/common/Header.jsx
  src/pages/Investment/Trading.jsx
  src/pages/Notification/Notification.jsx
  src/services/notifications.jsx
  src/store/reducers/Noti/notification.jsx
  src/utils/getNotificationDetails.jsx
  src/utils/touchDeleteHandler.jsx
Labels: ✨ feature

#60 feat: 로그인 기능 구현
  package.json
  src/components/Allowance/ChildHistoryListItem.jsx
  src/components/Auth/ChatBubble.jsx
  src/components/Auth/Input.jsx
  src/components/Mission/DueDateBottomSheet.jsx
  src/main.jsx
  src/pages/Auth/Login.jsx
  src/pages/Mission/Child/CreateMission.jsx
  src/pages/Mission/Child/Mission.jsx
  src/services/api.jsx
  src/services/cookie.js
  src/services/user.jsx
  src/utils/FetchSSE.jsx
  src/utils/isLogin.jsx
Labels: ✨ feature

#62 feat: 회원가입 완료
  src/components/Auth/Profile.jsx
  src/pages/Auth/Login.jsx
  src/pages/Auth/Signup.jsx
  src/services/api.jsx
  src/services/user.jsx
  src/store/reducers/Auth/user.jsx
  src/store/reducers/common/profile.jsx
  src/store/stores.jsx
Labels: ✨ feature

#64 Feature/63 invest,noti api
  src/assets/img/Invest/suggest.svg
  src/components/Investment/AreaChart.jsx
  src/components/Investment/CandleChart.jsx
  src/components/Investment/Chart.jsx
  src/components/Investment/Header.jsx
  src/components/Investment/Indicator.jsx
  src/components/Investment/PortfolioDonut.jsx
  src/components/Investment/PortfolioList.jsx
  src/components/Investment/StocksAbout.jsx
  src/components/Investment/StocksDetail.jsx
  src/components/Notification/Item.jsx
  src/components/Notification/NotiList.jsx
  src/components/common/Account.jsx
  src/components/common/Alert/CheckDeleteNoti.jsx
  src/components/common/Header.jsx
  src/pages/Auth/Login.jsx
  src/pages/Home/Home.jsx
  src/pages/Invest/Invest.jsx
  src/pages/Investment/Done.jsx
  src/pages/Investment/InvestMain.jsx
  src/pages/Investment/ParentSelection.jsx
  src/pages/Investment/Suggestion.jsx
  src/pages/Investment/Trading.jsx
  src/router/main-router.jsx
  src/services/api.jsx
  src/services/invest.jsx
  src/services/notifications.jsx
  src/services/stock.jsx
  src/store/reducers/Invest/invest.jsx
  src/store/reducers/Invest/portfolio.jsx
  src/store/reducers/Noti/notification.jsx
  src/store/stores.jsx
  src/utils/FetchSSE.jsx
  src/utils/PrivateRoute.jsx
  src/utils/groupDataByDate.jsx
Labels: ✨ feature

#65 feat: 마이페이지 api 연결 완료
  src/assets/data/profileImages.jsx
  src/components/Auth/Profile.jsx
  src/components/MyPage/Profile.jsx
  src/components/common/Member.jsx
  src/pages/MyPage/MemberManagement.jsx
  src/pages/MyPage/MyPage.jsx
  src/services/user.jsx
  src/utils/getCredibility.jsx
Labels: ✨ feature

#66 Feature/63 invest,noti api
  src/components/Investment/PortfolioDonut.jsx
  src/components/Investment/PortfolioList.jsx
  src/components/Investment/StocksDetail.jsx
  src/components/Investment/SuggestHistoryList.jsx
  src/components/Investment/SuggestHistoryListItem.jsx
  src/components/Investment/SuggestionDetail.jsx
  src/components/Investment/TradeHistoryList.jsx
  src/components/Notification/Item.jsx
  src/components/common/History/Filter.jsx
  src/index.css
  src/pages/Home/Home.jsx
  src/pages/Investment/StockList.jsx
  src/services/invest.jsx
  src/store/stores.jsx
  src/styles/GlobalStyles.jsx
  src/utils/FetchSSE.jsx
  src/utils/PrivateRoute.jsx
  src/utils/groupDataByDatetwo.jsx
Labels: ✨ feature
